# Generated by Django 3.2.6 on 2021-08-30 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210830_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={},
        ),
    ]
