# Generated by Django 3.2.6 on 2021-08-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210830_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='deposit',
        ),
        migrations.AddField(
            model_name='product',
            name='deposit',
            field=models.ManyToManyField(null=True, to='store.Deposit'),
        ),
    ]
