# Generated by Django 3.2.6 on 2021-08-31 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_factorytranslation_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslablePropertyFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='categoryttranslation',
            unique_together={('field', 'lang')},
        ),
        migrations.AlterUniqueTogether(
            name='deposittranslation',
            unique_together={('field', 'lang')},
        ),
        migrations.AlterUniqueTogether(
            name='producttranslation',
            unique_together={('field', 'lang')},
        ),
        migrations.CreateModel(
            name='PropertyTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.translablepropertyfields')),
                ('lang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.language')),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.productproperty')),
            ],
            options={
                'unique_together': {('field', 'lang')},
            },
        ),
    ]
