# Generated by Django 3.2.6 on 2021-08-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210830_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulksales',
            options={'verbose_name_plural': 'bulk sales'},
        ),
        migrations.AddField(
            model_name='product',
            name='price_per_unit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='promo_price',
            field=models.FloatField(default=0),
        ),
    ]
