# Generated by Django 3.2.6 on 2021-08-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210831_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='similars',
            field=models.ManyToManyField(blank=True, null=True, related_name='_store_product_similars_+', to='store.Product'),
        ),
    ]
