# Generated by Django 3.2.6 on 2021-08-31 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(default='c6a5208e', editable=False, max_length=8, unique=True),
        ),
    ]
