# Generated by Django 3.2.6 on 2021-09-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(db_table='tagged_items', to='store.Tag'),
        ),
        migrations.DeleteModel(
            name='TaggedItems',
        ),
    ]
