# Generated by Django 3.2.6 on 2021-08-31 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductLanguage',
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text='ISO 2 Letter Language Codes', max_length=2),
        ),
    ]
