# Generated by Django 3.2.6 on 2021-08-31 13:19

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(default=store.models.get_uuid_code, max_length=8),
        ),
    ]
