# Generated by Django 3.2.6 on 2021-08-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ISO 2 Letter Language Codes', max_length=2)),
            ],
        ),
        migrations.RenameModel(
            old_name='PostImage',
            new_name='ProductImage',
        ),
        migrations.AddField(
            model_name='product',
            name='similars',
            field=models.ManyToManyField(related_name='_store_product_similars_+', to='store.Product'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='store.Category'),
        ),
    ]
