# Generated by Django 3.2.6 on 2021-08-31 13:26

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(default=store.models.get_uuid_code, max_length=8, unique=True),
        ),
    ]
