# Generated by Django 3.2.6 on 2021-08-31 09:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_categoryttranslation_translablecategoryfields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
