# Generated by Django 3.2.6 on 2021-09-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_tagtranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagtranslation',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
