# Generated by Django 3.2.6 on 2021-09-10 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_tagtranslation_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagtranslation',
            old_name='Tag',
            new_name='tag',
        ),
        migrations.AlterUniqueTogether(
            name='tagtranslation',
            unique_together={('tag', 'lang', 'value')},
        ),
    ]
