# Generated by Django 3.2.6 on 2021-08-30 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210830_1259'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImage',
            new_name='PostImage',
        ),
    ]
