# Generated by Django 3.2.6 on 2021-09-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210910_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderticket',
            name='subject',
            field=models.CharField(default='', max_length=255),
        ),
    ]
