# Generated by Django 3.2.6 on 2021-08-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210830_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(help_text='no more 255 letters', max_length=255, null=True),
        ),
    ]
