# Generated by Django 3.2.6 on 2021-09-02 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210902_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='complete',
            new_name='placed',
        ),
    ]
