# Generated by Django 3.2.6 on 2021-08-30 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_productproperty_productpropertyrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_count', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='productproperty',
            options={'verbose_name_plural': 'product properties'},
        ),
        migrations.CreateModel(
            name='ProductBulkSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('product', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
                ('product_count', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.bulksales')),
            ],
        ),
    ]
