# Generated by Django 3.2.6 on 2021-09-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210902_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderticket',
            old_name='value',
            new_name='message',
        ),
        migrations.AddField(
            model_name='orderticket',
            name='type',
            field=models.IntegerField(choices=[(1, 'Order Status'), (2, 'Message')], default=2),
        ),
    ]
