# Generated by Django 3.2.6 on 2021-08-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210830_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_per_unit',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='promo_price',
            field=models.FloatField(null=True),
        ),
    ]
