# Generated by Django 3.2.6 on 2021-08-31 06:27

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210830_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='default_image',
            field=models.FileField(null=True, upload_to=store.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='promo_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(help_text='no more 255 letters', max_length=255, null=True),
        ),
    ]
