# Generated by Django 3.2.6 on 2021-09-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_orderticket_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderticket',
            name='message',
            field=models.TextField(default='no message'),
        ),
    ]
