# Generated by Django 3.2.6 on 2021-09-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_orderticket_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderticket',
            name='message',
            field=models.TextField(),
        ),
    ]
