# Generated by Django 3.2.6 on 2021-09-03 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categoryttranslation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='deposittranslation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='factorytranslation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='producttranslation',
            unique_together={('product', 'field', 'lang')},
        ),
        migrations.AlterUniqueTogether(
            name='propertytranslation',
            unique_together=set(),
        ),
    ]
